### ISSUE TITLE
SQLite Error

### ISSUE THREAD

**Issue by theFisher86** [flattermann/TCE-Relay#3]
Whenever I run TCE-Relay I get the following error:

```
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "TCE-RelayClient.py", line 124, in <module>
sqlite3.OperationalError: unable to open database file

```

on Windows 10...

**Comment by flattermann** [comment]
Is TCE installed in c:\TCE?

If not, please specify the path to TCE like:

TCE-RelayClient.exe --tce-path D;\TCE
